version: '3.8'
services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8077:80'
    environment:
      - PMA_HOST=db
    depends_on:
      - db
  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    restart: unless-stopped
    environment:
      MYSQL_PASSWORD: kogeki
      MYSQL_ROOT_PASSWORD: kogeki
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD:
  mueblesstgo-salary-ms:
    image: kogekii/salary-ms:latest
    ports:
      - '8004:8004'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/salary
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=kogeki
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  mueblesstgo-correo-ms:
    image: kogekii/correo-ms:latest
    ports:
      - '8003:8003'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/correo
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=kogeki
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  mueblesstgo-clock-ms:
    image: kogekii/clock-ms:latest
    ports:
      - '8002:8002'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/timesstamp
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=kogeki
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db
  mueblesstgo-calendar-ms:
    image: kogekii/calendar-ms:latest
    ports:
      - '8001:8001'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/calendar
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=kogeki
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - db